name: flutter_islamic_icons
description: Add color to your projects with dozens of beautiful Islamic icons.
version: 1.0.1
homepage: https://erbasaran.com
repository: https://github.com/erbasaran/flutter_islamic_icons
issue_tracker: https://github.com/erbasaran/flutter_islamic_icons/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: IslamicIcons
      fonts:
        - asset: assets/fonts/IslamicIcons.ttf
